# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d08ec895bc6d249e71e3fe8e00348d4e31bf8c9db32d06e5d8b1b2f2a57e1125f8f86bc50bc5c188f1835cdab52d85c9f49a449bbedde0e1613529344fcbe19e

test:
  secret_key_base: be4726df7a3503bb774eb2f742a5c2dd817f1ed05e74633a637a9318ebe51e1528e4e9d6359d7bb01c5a74c40a6ca3245696131d9ae64d1e4402edd0c4b43cae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
